version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: ecommerce
    ports:
      - "5460:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/seed_olist.sql:/docker-entrypoint-initdb.d/seed_olist.sql
    networks:
      ecommerce_net:
        ipv4_address: 172.20.0.23

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      ecommerce_net:
        ipv4_address: 172.20.0.24

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres
    networks:
      - ecommerce_net

networks:
  ecommerce_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data:
  metabase_data:
