name: ecommerce-ci
on:
    push:
        paths:
            - 'ecommerce-pipeline/**'

jobs:
    run-ci-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ecommerce-pipeline

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Spin up containers
              run: make up ENV_FILE=.env.dev

            - name: Wait for Airflow Webserver to be healthy
              run: make wait-for-webserver

            - name: Run CI test
              run: make ci

